### ISSUE TITLE
develop request

### ISSUE THREAD

**Issue by e6on** [pebble-examples/health-watchface#3]
Please add date, battery and bt icons and vibrate when bt disconnects to the watchface.
Custom font would be nice to. Here is an excample pic.
![wachfase](https://cloud.githubusercontent.com/assets/10757941/15438455/eca54aca-1ed4-11e6-9dd0-d29366892352.png)

**Comment by C-D-Lewis** [comment]
I will just add that this is a reference implementation for instructional purposes. Perhaps you could fork this and add the requested features.

**Comment by e6on** [comment]
Sorry, but I'm not a programmer and don't know how to add these features. I can read some of the code but I don't even find where in the code is the font size defined to make it bigger.

**Comment by edmund-k** [comment]
Hi @C-D-Lewis 

Could you please update the source to the latest and greatest version of Stride? Looking forward to add some of the mentioned infos (distance and date) and deriving a Stride+ watchface. Experimenting with this, I already experiencing that the current source is not rendering exact the same details (different shoe graphic, colors, fonts, design details, ...). Would be great to start with the current Stride design! Thanks!

Edmund

**Comment by C-D-Lewis** [comment]
Again, this is a reference implementation. I also don't work for Pebble anymore, so perhaps @orviwan can perform these modifications. However, adding much more complexity will make it less useful as an example.
